declare module "lucide-react" {
  import type { ComponentType, SVGProps } from "react";

  type LucideIcon = ComponentType<SVGProps<SVGSVGElement> & {
    size?: number | string;
    strokeWidth?: number | string;
    absoluteStrokeWidth?: boolean;
  }>;

  export const AlertTriangle: LucideIcon;
  export const ArrowLeft: LucideIcon;
  export const ArrowRight: LucideIcon;
  export const ArrowUpRight: LucideIcon;
  export const Battery: LucideIcon;
  export const BookOpen: LucideIcon;
  export const Bookmark: LucideIcon;
  export const Box: LucideIcon;
  export const Check: LucideIcon;
  export const CheckCircle: LucideIcon;
  export const ChevronDown: LucideIcon;
  export const CircuitBoard: LucideIcon;
  export const Clapperboard: LucideIcon;
  export const Clock: LucideIcon;
  export const Clock3: LucideIcon;
  export const ClipboardList: LucideIcon;
  export const Copy: LucideIcon;
  export const Cpu: LucideIcon;
  export const Cuboid: LucideIcon;
  export const Database: LucideIcon;
  export const Download: LucideIcon;
  export const ExternalLink: LucideIcon;
  export const Eye: LucideIcon;
  export const Film: LucideIcon;
  export const FlaskConical: LucideIcon;
  export const GitBranch: LucideIcon;
  export const GitFork: LucideIcon;
  export const Handshake: LucideIcon;
  export const History: LucideIcon;
  export const Info: LucideIcon;
  export const KeyRound: LucideIcon;
  export const LayoutDashboard: LucideIcon;
  export const Layers: LucideIcon;
  export const LoaderCircle: LucideIcon;
  export const Mail: LucideIcon;
  export const Maximize2: LucideIcon;
  export const Menu: LucideIcon;
  export const MessageSquare: LucideIcon;
  export const Minimize2: LucideIcon;
  export const Monitor: LucideIcon;
  export const MoreHorizontal: LucideIcon;
  export const Moon: LucideIcon;
  export const Palette: LucideIcon;
  export const Paperclip: LucideIcon;
  export const PanelLeftClose: LucideIcon;
  export const PanelLeftOpen: LucideIcon;
  export const Pin: LucideIcon;
  export const Plus: LucideIcon;
  export const Printer: LucideIcon;
  export const Radio: LucideIcon;
  export const RefreshCw: LucideIcon;
  export const Save: LucideIcon;
  export const Search: LucideIcon;
  export const Settings: LucideIcon;
  export const ShieldCheck: LucideIcon;
  export const Sliders: LucideIcon;
  export const SlidersHorizontal: LucideIcon;
  export const Snowflake: LucideIcon;
  export const Sparkles: LucideIcon;
  export const Square: LucideIcon;
  export const Sun: LucideIcon;
  export const Terminal: LucideIcon;
  export const Trash2: LucideIcon;
  export const Volume2: LucideIcon;
  export const Wrench: LucideIcon;
  export const X: LucideIcon;
}
