"use client";

import React, { useEffect, useMemo, useState } from "react";
import {
  ArrowLeft,
  ArrowRight,
  Clock3,
  Cpu,
  MessageSquare,
  Star,
  Trash2,
} from "lucide-react";

export type ProjectGalleryItem = {
  key: string;
  title: string;
  projectId: string;
  chatId: string;
  canChat: boolean;
  creatorDisplay: string;
  creatorImageUrl: string | null;
  createdAt: string | null;
  partsCount: number;
  starCount: number;
  image: ProjectImageCandidate | null;
  imageLoading: boolean;
};

// Keep pagination stable across server render and hydration. The grid itself is
// responsive; changing the item count after mount caused the whole page to jump.
export const PROJECT_GALLERY_PAGE_SIZE = 6;

export type ProjectImageCandidate = {
  src: string;
  label: string;
  viewId?: string;
  prompt?: string;
  dimensions?: string;
};

function validRemoteImageUrl(value: any): string | null {
  if (typeof value !== "string") return null;
  const trimmed = value.trim();
  if (!trimmed) return null;
  try {
    const url = new URL(trimmed);
    if (url.protocol !== "http:" && url.protocol !== "https:") return null;
    return trimmed;
  } catch {
    return null;
  }
}

function safeImageContentType(value: any) {
  return typeof value === "string" && /^image\/[a-z0-9.+-]+$/i.test(value.trim()) ? value.trim() : "image/png";
}

function normalImageSrc(value: any, contentType?: any): string | null {
  if (typeof value !== "string") return null;
  const trimmed = value.trim();
  if (!trimmed) return null;
  if (trimmed.startsWith("data:image/") || validRemoteImageUrl(trimmed)) return trimmed;
  const compact = trimmed.replace(/\s+/g, "");
  if (/^[A-Za-z0-9+/]+={0,2}$/.test(compact) && compact.length > 20) {
    return `data:${safeImageContentType(contentType)};base64,${compact}`;
  }
  return trimmed;
}

export function previewableImageSrc(value: any): string | null {
  if (typeof value !== "string") return null;
  const trimmed = value.trim();
  if (!trimmed) return null;
  if (trimmed.startsWith("data:image/") || validRemoteImageUrl(trimmed)) return normalImageSrc(trimmed);
  const compact = trimmed.replace(/\s+/g, "");
  if (/^[A-Za-z0-9+/]+={0,2}$/.test(compact) && compact.length > 20) return normalImageSrc(trimmed);
  return null;
}

export function resolveProjectImageCandidates(metadata: Record<string, any> = {}, showModelName = false): ProjectImageCandidate[] {
  const generatedLabel = showModelName
    ? `Generated by ${metadata.product_image_model || metadata.image_output_model || "image model"}`
    : "Generated product image";
  const sequence = Array.isArray(metadata.product_visual_sequence) ? metadata.product_visual_sequence : [];
  const sequenceCandidates = sequence
    .filter((item: any) => {
      if (!item || typeof item !== "object") return false;
      const viewId = typeof item.view_id === "string" ? item.view_id.trim().toLowerCase() : "";
      const labelKey = typeof item.label === "string" ? item.label.trim().toLowerCase().replace(/\s+/g, "-") : "";
      return viewId !== "diagram" && labelKey !== "subsystem-physical-layout";
    })
    .map((item: any): ProjectImageCandidate | null => {
      if (!item || typeof item !== "object") return null;
      const src =
        normalImageSrc(item.url, item.content_type) ||
        normalImageSrc(item.data, item.content_type) ||
        normalImageSrc(metadata[`product_${item.view_id}_image_url`], metadata[`product_${item.view_id}_image_content_type`]) ||
        normalImageSrc(metadata[`product_${item.view_id}_image_data`], metadata[`product_${item.view_id}_image_content_type`]);
      if (!src) return null;
      return {
        src,
        label: typeof item.label === "string" && item.label.trim() ? item.label : generatedLabel,
        viewId: typeof item.view_id === "string" ? item.view_id : undefined,
        prompt: typeof item.prompt === "string" ? item.prompt : undefined,
      };
    })
    .filter((candidate: ProjectImageCandidate | null): candidate is ProjectImageCandidate => Boolean(candidate));

  const stagedCandidates: Array<ProjectImageCandidate | null> = [
    normalImageSrc(metadata.product_case_image_url, metadata.product_case_image_content_type) ||
    normalImageSrc(metadata.product_case_image_data, metadata.product_case_image_content_type)
      ? {
          src:
            normalImageSrc(metadata.product_case_image_url, metadata.product_case_image_content_type) ||
            normalImageSrc(metadata.product_case_image_data, metadata.product_case_image_content_type) ||
            "",
          label: "Case exterior",
          viewId: "case",
        }
      : null,
    normalImageSrc(metadata.product_inside_image_url, metadata.product_inside_image_content_type) ||
    normalImageSrc(metadata.product_inside_image_data, metadata.product_inside_image_content_type)
      ? {
          src:
            normalImageSrc(metadata.product_inside_image_url, metadata.product_inside_image_content_type) ||
            normalImageSrc(metadata.product_inside_image_data, metadata.product_inside_image_content_type) ||
            "",
          label: "Transparent top-down assembly",
          viewId: "inside",
        }
      : null,
  ];

  const productUrl = validRemoteImageUrl(metadata.product_image_url);
  const productData = normalImageSrc(metadata.product_image_data, metadata.product_image_content_type);
  const referenceUrl = validRemoteImageUrl(metadata.reference_image_url);
  const referenceData = normalImageSrc(metadata.reference_image_data, metadata.reference_image_content_type);
  const hasGeneratedViews = sequenceCandidates.length > 0 || stagedCandidates.some(Boolean);
  const candidates: Array<ProjectImageCandidate | null> = [
    ...sequenceCandidates,
    ...stagedCandidates,
    !hasGeneratedViews && productUrl ? { src: productUrl, label: generatedLabel } : null,
    !hasGeneratedViews && productData ? { src: productData, label: generatedLabel } : null,
    referenceUrl ? { src: referenceUrl, label: "Uploaded hardware reference" } : null,
    referenceData ? { src: referenceData, label: "Uploaded hardware reference" } : null,
  ];

  const unique = new Map<string, ProjectImageCandidate>();
  candidates
    .filter((candidate): candidate is ProjectImageCandidate => Boolean(candidate && candidate.src))
    .forEach((candidate) => {
      if (!unique.has(candidate.src)) unique.set(candidate.src, candidate);
    });
  return Array.from(unique.values());
}

function formatProjectAge(value: string | null) {
  if (!value) return "";
  const createdAt = new Date(value).getTime();
  if (Number.isNaN(createdAt)) return "";
  const elapsedMs = Math.max(0, Date.now() - createdAt);
  const hours = Math.floor(elapsedMs / (60 * 60 * 1000));
  if (hours < 24) return hours <= 0 ? "Today" : `${hours}h`;
  const days = Math.floor(hours / 24);
  if (days < 31) return days === 1 ? "1 day" : `${days} days`;
  const months = Math.floor(days / 30);
  return months === 1 ? "1 month" : `${months} months`;
}

export function buildProjectGalleryItems(
  projectHistory: any[],
  projectImages: Record<string, ProjectImageCandidate | null>,
  showModelName = false,
): ProjectGalleryItem[] {
  return projectHistory
    .filter((project: any) => project?.project_id)
    .map((project: any) => {
      const projectId = String(project.project_id);
      const chatId = String(project.chat_id || projectId);
      const summaryImage =
        resolveProjectImageCandidates({
          product_visual_sequence: project.product_visual_sequence,
          product_image_url: project.product_image_url,
          product_image_data: project.product_image_data,
          product_image_content_type: project.product_image_content_type,
          product_image_model: project.product_image_model,
          image_output_model: project.image_output_model,
        }, showModelName)[0] || null;
      const fetchedImage = projectImages[projectId];
      return {
        key: projectId,
        title: project.title || "Untitled project",
        projectId,
        chatId,
        canChat: Boolean(project.can_chat ?? project.canChat),
        creatorDisplay:
          typeof project.creator_username === "string" && project.creator_username.trim()
            ? project.creator_username.trim()
            : typeof project.creator_display === "string" && project.creator_display.trim()
              ? project.creator_display.trim()
              : "unknown",
        creatorImageUrl:
          typeof project.creator_image_url === "string" && project.creator_image_url.trim()
            ? project.creator_image_url.trim()
            : typeof project.creatorImageUrl === "string" && project.creatorImageUrl.trim()
              ? project.creatorImageUrl.trim()
              : null,
        createdAt: typeof project.created_at === "string" && project.created_at ? project.created_at : null,
        partsCount: Math.max(0, Number(project.parts_count || project.partsCount || 0)),
        starCount: Math.max(0, Number(project.star_count || project.starCount || 0)),
        image: fetchedImage || summaryImage,
        imageLoading: !summaryImage && fetchedImage === undefined,
      };
    });
}

export function ProjectGallery({
  sectionRef,
  items,
  title = "Projects",
  loading = false,
  onOpenProjectPage,
  onDeleteProject,
  onVisibleProjectIdsChange,
  totalItems,
  currentPage: controlledPage,
  onPageChange,
  standalone = false,
}: {
  sectionRef: React.RefObject<HTMLElement | null>;
  items: ProjectGalleryItem[];
  title?: string;
  loading?: boolean;
  onOpenProjectPage: (projectId: string) => void;
  onDeleteProject?: (item: ProjectGalleryItem) => void;
  onVisibleProjectIdsChange?: (projectIds: string[]) => void;
  totalItems?: number;
  currentPage?: number;
  onPageChange?: (page: number) => void;
  standalone?: boolean;
}) {
  const pageSize = PROJECT_GALLERY_PAGE_SIZE;
  const [localPage, setLocalPage] = useState(0);
  const serverPaginated = typeof totalItems === "number" && typeof controlledPage === "number" && Boolean(onPageChange);
  const currentPage = serverPaginated ? controlledPage : localPage;
  const total = serverPaginated ? Math.max(0, totalItems) : items.length;
  const pageCount = Math.max(1, Math.ceil(total / pageSize));
  const safePage = Math.min(currentPage, pageCount - 1);
  const firstVisibleItem = safePage * pageSize;
  const visibleItems = useMemo(
    () => serverPaginated ? items : items.slice(firstVisibleItem, firstVisibleItem + pageSize),
    [firstVisibleItem, items, pageSize, serverPaginated]
  );
  const visibleProjectIds = useMemo(
    () => visibleItems.map((item) => item.projectId),
    [visibleItems]
  );
  const showingStart = total ? firstVisibleItem + 1 : 0;
  const showingEnd = Math.min(total, firstVisibleItem + visibleItems.length);
  const pageMarkers = buildProjectGalleryPageMarkers(safePage, pageCount);

  useEffect(() => {
    if (!serverPaginated) setLocalPage(0);
  }, [items.length, pageSize, serverPaginated]);

  useEffect(() => {
    if (safePage !== currentPage) {
      if (serverPaginated) onPageChange?.(safePage);
      else setLocalPage(safePage);
    }
  }, [currentPage, onPageChange, safePage, serverPaginated]);

  useEffect(() => {
    onVisibleProjectIdsChange?.(visibleProjectIds);
  }, [onVisibleProjectIdsChange, visibleProjectIds]);

  const goToPage = (page: number) => {
    const nextPage = Math.min(Math.max(page, 0), pageCount - 1);
    if (serverPaginated) onPageChange?.(nextPage);
    else setLocalPage(nextPage);
  };

  return (
    <section ref={sectionRef} id="all-projects" className={standalone ? "" : "mt-16 border-t border-[#292b31] pt-12"}>
      <div className="mb-6 flex flex-col gap-3">
        <div>
          <div className="flex items-center gap-3">
            <span className="flex h-9 w-9 items-center justify-center border border-[#2c2f37] bg-black text-white">
              <Cpu className="h-4 w-4" />
            </span>
            <h2 className="text-2xl font-black uppercase tracking-[0.22em] text-white">{title}</h2>
          </div>
          <p className="mt-4 text-sm leading-6 text-slate-500">
            {loading ? "Loading projects..." : `${total} saved projects.`}
          </p>
        </div>
      </div>

      {loading ? (
        <ProjectGallerySkeleton count={pageSize} />
      ) : total && visibleItems.length ? (
        <>
          <div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4">
            {visibleItems.map((item) => (
              <ProjectGalleryCard
                key={item.key}
                item={item}
                onOpen={() => onOpenProjectPage(item.projectId)}
                onDelete={onDeleteProject && item.canChat ? () => onDeleteProject(item) : undefined}
              />
            ))}
          </div>

          {pageCount > 1 && (
            <div className="mt-5 flex flex-col gap-3 border border-[#2c2f37] bg-[#17181d] p-3 sm:flex-row sm:items-center sm:justify-between">
              <div className="text-xs font-black uppercase tracking-[0.14em] text-slate-500">
                Showing {showingStart}-{showingEnd} of {total}
              </div>

              <div className="grid grid-cols-[44px_minmax(0,1fr)_44px] gap-2 sm:flex sm:items-center">
                <button
                  type="button"
                  onClick={() => goToPage(safePage - 1)}
                  disabled={safePage === 0}
                  className="inline-flex h-10 w-11 items-center justify-center border border-[#2a2c33] text-white transition hover:bg-white hover:text-black disabled:cursor-not-allowed disabled:opacity-40 disabled:hover:bg-transparent disabled:hover:text-white"
                  aria-label="Previous projects page"
                >
                  <ArrowLeft className="h-4 w-4" />
                </button>

                <div className="hidden items-center gap-2 sm:flex">
                  {pageMarkers.map((marker, index) => (
                    marker === "gap" ? (
                      <span
                        key={`gap-${index}`}
                        className="flex h-10 min-w-7 items-center justify-center text-xs font-black text-slate-600"
                      >
                        ...
                      </span>
                    ) : (
                      <button
                        key={marker}
                        type="button"
                        onClick={() => goToPage(marker)}
                        aria-current={marker === safePage ? "page" : undefined}
                        className={`h-10 min-w-10 border px-3 text-xs font-black uppercase transition ${
                          marker === safePage
                            ? "border-white bg-white text-black"
                            : "border-[#2a2c33] text-slate-400 hover:bg-white hover:text-black"
                        }`}
                      >
                        {marker + 1}
                      </button>
                    )
                  ))}
                </div>

                <div className="flex h-10 items-center justify-center border border-[#2a2c33] text-xs font-black uppercase tracking-[0.14em] text-slate-400 sm:hidden">
                  Page {safePage + 1} / {pageCount}
                </div>

                <button
                  type="button"
                  onClick={() => goToPage(safePage + 1)}
                  disabled={safePage >= pageCount - 1}
                  className="inline-flex h-10 w-11 items-center justify-center border border-[#2a2c33] text-white transition hover:bg-white hover:text-black disabled:cursor-not-allowed disabled:opacity-40 disabled:hover:bg-transparent disabled:hover:text-white"
                  aria-label="Next projects page"
                >
                  <ArrowRight className="h-4 w-4" />
                </button>
              </div>
            </div>
          )}
        </>
      ) : (
        <div className="border border-[#2c2f37] bg-[#17181d] p-8 text-sm leading-6 text-slate-500">
          No saved projects yet.
        </div>
      )}
    </section>
  );
}

function buildProjectGalleryPageMarkers(currentPage: number, pageCount: number): Array<number | "gap"> {
  if (pageCount <= 7) {
    return Array.from({ length: pageCount }, (_, index) => index);
  }

  const markers = new Set([0, pageCount - 1, currentPage]);

  if (currentPage > 0) {
    markers.add(currentPage - 1);
  }

  if (currentPage < pageCount - 1) {
    markers.add(currentPage + 1);
  }

  const sortedMarkers = Array.from(markers).sort((a, b) => a - b);
  return sortedMarkers.flatMap((marker, index) => {
    const previousMarker = sortedMarkers[index - 1];
    return index > 0 && marker - previousMarker > 1 ? ["gap", marker] : [marker];
  });
}

function ProjectGallerySkeleton({ count }: { count: number }) {
  const skeletonItems = Array.from({ length: Math.max(1, count) }, (_, index) => index);
  return (
    <div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4" aria-label="Loading projects">
      {skeletonItems.map((item) => (
        <div
          key={item}
          className="overflow-hidden border border-[#2c2f37] bg-[#17181d]"
        >
          <div className="aspect-square overflow-hidden border-b border-[#2c2f37] bg-[#0f1014] sm:aspect-[4/3]">
            <ProjectImageLoadingPanel />
          </div>
          <div className="flex min-h-[150px] flex-col justify-between gap-3 p-4">
            <div className="space-y-2">
              <div className="h-4 w-4/5 animate-pulse bg-[#252832]" />
              <div className="h-4 w-3/5 animate-pulse bg-[#252832]" />
            </div>
            <div className="flex gap-4">
              <div className="h-3 w-14 animate-pulse bg-[#252832]" />
              <div className="h-3 w-10 animate-pulse bg-[#252832]" />
              <div className="h-3 w-12 animate-pulse bg-[#252832]" />
            </div>
            <div className="flex items-center justify-between gap-3">
              <div className="h-4 w-24 animate-pulse bg-[#252832]" />
              <div className="h-9 w-24 animate-pulse border border-cyan-300/20 bg-[#111820]" />
            </div>
          </div>
        </div>
      ))}
    </div>
  );
}

function ProjectImageLoadingPanel() {
  return (
    <div className="flex h-full flex-col items-center justify-center gap-3 px-5 text-center">
      <div className="h-2 w-28 overflow-hidden bg-[#252832]">
        <div className="h-full w-full animate-pulse bg-cyan-300/60" />
      </div>
      <div className="text-xs font-black uppercase tracking-[0.18em] text-slate-500">
        Loading image
      </div>
    </div>
  );
}

function ProjectGalleryCard({
  item,
  onOpen,
  onDelete,
}: {
  item: ProjectGalleryItem;
  onOpen: () => void;
  onDelete?: () => void;
}) {
  const ageLabel = formatProjectAge(item.createdAt);
  return (
    <article
      role="link"
      tabIndex={0}
      onClick={onOpen}
      onKeyDown={(event) => {
        if (event.key === "Enter" || event.key === " ") {
          event.preventDefault();
          onOpen();
        }
      }}
      className="group cursor-pointer overflow-hidden border border-[#2c2f37] bg-[#17181d] outline-none transition hover:border-cyan-300/35 focus-visible:border-cyan-300"
      aria-label={`View project ${item.title}`}
    >
      <div className="aspect-square overflow-hidden border-b border-[#2c2f37] bg-[#0f1014] sm:aspect-[4/3]">
        {item.image ? (
          <img
            src={item.image.src}
            alt={`${item.title} preview`}
            className="h-full w-full object-contain p-2 transition duration-300 group-hover:scale-[1.015] sm:object-cover sm:p-0"
          />
        ) : item.imageLoading ? (
          <ProjectImageLoadingPanel />
        ) : (
          <div className="flex h-full items-center justify-center text-xs font-black uppercase tracking-[0.18em] text-slate-600">
            No image
          </div>
        )}
      </div>

      <div className="flex min-h-[150px] flex-col justify-between gap-3 p-4">
        <h3 className="line-clamp-2 min-h-10 break-words text-sm font-black uppercase leading-5 tracking-[0.08em] text-white">
          {item.title}
        </h3>
        <div className="flex min-w-0 flex-wrap items-center gap-x-4 gap-y-2 text-sm font-bold text-slate-500">
          <span className="whitespace-nowrap">{item.partsCount} parts</span>
          <span className="inline-flex items-center gap-1 whitespace-nowrap text-amber-300">
            <Star className="h-3.5 w-3.5 fill-current" />
            {item.starCount}
          </span>
          {ageLabel && (
            <span className="inline-flex items-center gap-1 whitespace-nowrap">
              <Clock3 className="h-3.5 w-3.5" />
              {ageLabel}
            </span>
          )}
        </div>
        <div className="flex min-w-0 items-center justify-between gap-3">
          <div className="flex min-w-0 items-center gap-2 text-sm font-bold text-slate-500">
            {item.creatorImageUrl ? (
              <img
                src={item.creatorImageUrl}
                alt=""
                className="h-5 w-5 shrink-0 border border-[#2c2f37] object-cover"
              />
            ) : (
              <span className="h-3.5 w-3.5 shrink-0 border border-emerald-300 bg-emerald-400 shadow-[inset_6px_0_0_#f472b6]" />
            )}
            <span className="truncate">{item.creatorDisplay}</span>
          </div>
          <div className="flex shrink-0 items-center gap-2">
            {onDelete && (
              <button
                type="button"
                onClick={(event) => {
                  event.stopPropagation();
                  onDelete();
                }}
                onKeyDown={(event) => event.stopPropagation()}
                className="inline-flex h-9 w-9 items-center justify-center border border-red-400/35 text-red-200 transition hover:bg-red-400 hover:text-black"
                aria-label={`Delete ${item.title}`}
              >
                <Trash2 className="h-4 w-4" />
              </button>
            )}
            {item.canChat && (
              <span className="inline-flex h-9 shrink-0 items-center justify-center gap-2 border border-cyan-300/35 px-3 text-xs font-black uppercase text-cyan-100 transition group-hover:bg-cyan-300 group-hover:text-black">
                <MessageSquare className="h-4 w-4 shrink-0" />
                <span className="truncate">Your project</span>
              </span>
            )}
          </div>
        </div>
      </div>
    </article>
  );
}
