export const HARDWARE_REFERENCE_VIEW_ID = "reference";
export const HARDWARE_REFERENCE_LABEL = "Hardware reference";

export type ProjectImageCandidate = {
  src: string;
  label: string;
  viewId?: string;
  prompt?: string;
  dimensions?: string;
};

function validRemoteImageUrl(value: any): string | null {
  if (typeof value !== "string") return null;
  const trimmed = value.trim();
  if (!trimmed) return null;
  try {
    const url = new URL(trimmed);
    if (url.protocol !== "http:" && url.protocol !== "https:") return null;
    return trimmed;
  } catch {
    return null;
  }
}

function safeImageContentType(value: any) {
  return typeof value === "string" && /^image\/[a-z0-9.+-]+$/i.test(value.trim()) ? value.trim() : "image/png";
}

function normalImageSrc(value: any, contentType?: any): string | null {
  if (typeof value !== "string") return null;
  const trimmed = value.trim();
  if (!trimmed) return null;
  if (trimmed.startsWith("data:image/") || validRemoteImageUrl(trimmed)) return trimmed;
  const compact = trimmed.replace(/\s+/g, "");
  if (/^[A-Za-z0-9+/]+={0,2}$/.test(compact) && compact.length > 20) {
    return `data:${safeImageContentType(contentType)};base64,${compact}`;
  }
  return trimmed;
}

export function previewableImageSrc(value: any): string | null {
  if (typeof value !== "string") return null;
  const trimmed = value.trim();
  if (!trimmed) return null;
  if (trimmed.startsWith("data:image/") || validRemoteImageUrl(trimmed)) return normalImageSrc(trimmed);
  const compact = trimmed.replace(/\s+/g, "");
  if (/^[A-Za-z0-9+/]+={0,2}$/.test(compact) && compact.length > 20) return normalImageSrc(trimmed);
  return null;
}

export function isHardwareReferenceCandidate(candidate: Pick<ProjectImageCandidate, "label" | "viewId">) {
  const viewId = (candidate.viewId || "").trim().toLowerCase();
  if (viewId === HARDWARE_REFERENCE_VIEW_ID) return true;
  const label = candidate.label.trim().toLowerCase();
  return label.includes("hardware reference") || label.includes("uploaded hardware");
}

export function hardwareReferenceSrcFromChatMessages(
  messages: Array<{ role?: string; imagePreview?: string | null }> = [],
): string | null {
  for (let index = messages.length - 1; index >= 0; index -= 1) {
    const preview = messages[index]?.role === "user" ? messages[index]?.imagePreview : null;
    if (typeof preview === "string" && preview.trim()) return preview.trim();
  }
  return null;
}

export function withHardwareReferenceMetadata(
  metadata: Record<string, any> = {},
  referenceSrc?: string | null,
): Record<string, any> {
  if (metadata.reference_image_url || metadata.reference_image_data || !referenceSrc) {
    return metadata;
  }
  const src = previewableImageSrc(referenceSrc);
  if (!src) return metadata;
  return { ...metadata, reference_image_data: src };
}

export function resolveProjectImageCandidates(metadata: Record<string, any> = {}, showModelName = false): ProjectImageCandidate[] {
  const generatedLabel = showModelName
    ? `Generated by ${metadata.product_image_model || metadata.image_output_model || "image model"}`
    : "Generated product image";
  const sequence = Array.isArray(metadata.product_visual_sequence) ? metadata.product_visual_sequence : [];
  const sequenceCandidates = sequence
    .filter((item: any) => {
      if (!item || typeof item !== "object") return false;
      const viewId = typeof item.view_id === "string" ? item.view_id.trim().toLowerCase() : "";
      const labelKey = typeof item.label === "string" ? item.label.trim().toLowerCase().replace(/\s+/g, "-") : "";
      return viewId !== "diagram" && labelKey !== "subsystem-physical-layout";
    })
    .map((item: any): ProjectImageCandidate | null => {
      if (!item || typeof item !== "object") return null;
      const src =
        normalImageSrc(item.url, item.content_type) ||
        normalImageSrc(item.data, item.content_type) ||
        normalImageSrc(metadata[`product_${item.view_id}_image_url`], metadata[`product_${item.view_id}_image_content_type`]) ||
        normalImageSrc(metadata[`product_${item.view_id}_image_data`], metadata[`product_${item.view_id}_image_content_type`]);
      if (!src) return null;
      return {
        src,
        label: typeof item.label === "string" && item.label.trim() ? item.label : generatedLabel,
        viewId: typeof item.view_id === "string" ? item.view_id : undefined,
        prompt: typeof item.prompt === "string" ? item.prompt : undefined,
      };
    })
    .filter((candidate: ProjectImageCandidate | null): candidate is ProjectImageCandidate => Boolean(candidate));

  const stagedCandidates: Array<ProjectImageCandidate | null> = [
    normalImageSrc(metadata.product_case_image_url, metadata.product_case_image_content_type) ||
    normalImageSrc(metadata.product_case_image_data, metadata.product_case_image_content_type)
      ? {
          src:
            normalImageSrc(metadata.product_case_image_url, metadata.product_case_image_content_type) ||
            normalImageSrc(metadata.product_case_image_data, metadata.product_case_image_content_type) ||
            "",
          label: "Case exterior",
          viewId: "case",
        }
      : null,
    normalImageSrc(metadata.product_inside_image_url, metadata.product_inside_image_content_type) ||
    normalImageSrc(metadata.product_inside_image_data, metadata.product_inside_image_content_type)
      ? {
          src:
            normalImageSrc(metadata.product_inside_image_url, metadata.product_inside_image_content_type) ||
            normalImageSrc(metadata.product_inside_image_data, metadata.product_inside_image_content_type) ||
            "",
          label: "Transparent top-down assembly",
          viewId: "inside",
        }
      : null,
  ];

  const productUrl = validRemoteImageUrl(metadata.product_image_url);
  const productData = normalImageSrc(metadata.product_image_data, metadata.product_image_content_type);
  const referenceUrl = validRemoteImageUrl(metadata.reference_image_url);
  const referenceData = normalImageSrc(metadata.reference_image_data, metadata.reference_image_content_type);
  const hasGeneratedViews = sequenceCandidates.length > 0 || stagedCandidates.some(Boolean);
  const referenceCandidate = referenceUrl
    ? { src: referenceUrl, label: HARDWARE_REFERENCE_LABEL, viewId: HARDWARE_REFERENCE_VIEW_ID }
    : referenceData
      ? { src: referenceData, label: HARDWARE_REFERENCE_LABEL, viewId: HARDWARE_REFERENCE_VIEW_ID }
      : null;
  const candidates: Array<ProjectImageCandidate | null> = [
    ...sequenceCandidates,
    ...stagedCandidates,
    !hasGeneratedViews && productUrl ? { src: productUrl, label: generatedLabel } : null,
    !hasGeneratedViews && productData ? { src: productData, label: generatedLabel } : null,
    referenceCandidate,
  ];

  const unique = new Map<string, ProjectImageCandidate>();
  candidates
    .filter((candidate): candidate is ProjectImageCandidate => Boolean(candidate && candidate.src))
    .forEach((candidate) => {
      if (!unique.has(candidate.src)) unique.set(candidate.src, candidate);
    });
  return Array.from(unique.values());
}
