"""No native CAD required: real HTTP client against a deterministic fake worker."""
import hashlib
import json
from uuid import uuid4

import httpx
import pytest

from apps.api.slicing_worker import SlicingWorker, WorkerError, SETTINGS

SOURCE = b"ISO-10303-21; test fixture"
DIGEST = hashlib.sha256(SOURCE).hexdigest()
TOKEN = "test-only-not-a-real-credential-12345678"
PROJECT = str(uuid4())
JOB = str(uuid4())
GCODE = b"; generated by PrusaSlicer 2.9.6\nM190 S60\nG1 X110 Y110 Z0.2 E1\n"


def job(**updates):
    return {"job_id": JOB, "project_id": PROJECT, "printer_profile": "ender3", "material": "pla",
            "settings": dict(SETTINGS), "source_format": "step", "status": "running",
            "idempotency_key": f"forma-ender-v1:{DIGEST}:nonce", **updates}


def client(handler):
    return SlicingWorker("https://worker.example", TOKEN, transport=httpx.MockTransport(handler))


def test_upload_poll_download_without_cad_or_orca():
    calls = []
    def handle(request):
        calls.append((request.method, request.url.path))
        assert request.headers["authorization"] == f"Bearer {TOKEN}"
        if request.url.path == "/slice":
            payload = json.loads(request.content)
            assert payload["printer_profile"] == "ender3"
            assert payload["source_format"] == "step"
            assert payload["settings"] == SETTINGS
            assert len(payload["idempotency_key"]) <= 128
            return httpx.Response(202, json={"job": job(status="awaiting_upload"), "upload_path": "https://evil.example/steal"})
        if request.url.path.endswith("/source"):
            assert request.content == SOURCE
            return httpx.Response(202, json={"job": job(status="queued")})
        if request.url.path.endswith("/artifact"):
            return httpx.Response(200, content=GCODE, headers={"etag": f'"sha256-{hashlib.sha256(GCODE).hexdigest()}"'})
        return httpx.Response(200, json={"job": job(status="completed", slicer="prusaslicer")})
    worker = client(handle)
    assert worker.start(PROJECT, DIGEST, SOURCE)["status"] == "queued"
    completed = worker.status(JOB, PROJECT, DIGEST)
    assert worker.artifact(completed) == (GCODE, hashlib.sha256(GCODE).hexdigest())
    assert calls == [("POST", "/slice"), ("PUT", f"/jobs/{JOB}/source"),
                     ("GET", f"/jobs/{JOB}"), ("GET", f"/jobs/{JOB}/artifact")]


@pytest.mark.parametrize("url", ["http://public.example", "file:///tmp/a", "https://u:p@host", "https://host?token=x", "https://host/#x", ""])
def test_reject_insecure_or_credential_urls(url):
    with pytest.raises(WorkerError): SlicingWorker(url, TOKEN)


@pytest.mark.parametrize("url", ["http://127.0.0.1:8790", "http://localhost:8790", "https://worker.example"])
def test_valid_deployment_addresses(url):
    assert SlicingWorker(url, TOKEN).url == url


@pytest.mark.parametrize("updates", [{"project_id": "another-owner-project"}, {"printer_profile": "bambu-a1-mini"},
    {"source_format": "stl"}, {"settings": {"infill_percent": 100}}, {"material": "abs"},
    {"idempotency_key": "old-revision"}])
def test_reject_cross_project_revision_or_settings(updates):
    worker = client(lambda request: httpx.Response(200, json={"job": job(**updates)}))
    with pytest.raises(WorkerError, match="does not match"): worker.status(JOB, PROJECT, DIGEST)


def test_invalid_id_does_not_make_request():
    worker = client(lambda request: pytest.fail("must not request"))
    with pytest.raises(WorkerError): worker.status("../../secret", PROJECT, DIGEST)


def test_corrupt_source_is_never_uploaded():
    worker = client(lambda request: pytest.fail("must not request"))
    with pytest.raises(WorkerError, match="integrity"): worker.start(PROJECT, DIGEST, b"changed")


def test_wrong_checksum_is_not_returned():
    worker = client(lambda request: httpx.Response(200, content=GCODE, headers={"etag": '"wrong"'}))
    with pytest.raises(WorkerError, match="integrity"): worker.artifact(job(status="completed", slicer="prusaslicer"))


def test_redirect_does_not_leak_token():
    calls = []
    def handler(request):
        calls.append(str(request.url))
        return httpx.Response(302, headers={"location": "https://evil.example"})
    with pytest.raises(WorkerError): client(handler).json("GET", "/capabilities")
    assert calls == ["https://worker.example/capabilities"]


def test_capabilities_only_exposes_ender_not_worker_paths():
    worker = client(lambda r: httpx.Response(200, json={"api_version": 1, "source_formats": ["step"], "printers": [
        {"id": "ender3", "slicer": "prusaslicer", "missing_profile_files": []}, {"id": "bambu-a1-mini"}]}))
    caps = worker.capabilities()
    assert len(caps) == 1 and caps[0]["available"] is True
    assert caps[0]["printer_id"] == "creality_ender_3_04"
    assert TOKEN not in json.dumps(caps)


def test_offline_worker_is_unavailable_not_false_success():
    def handler(request): raise httpx.ConnectError("secret worker path", request=request)
    caps = client(handler).capabilities()
    assert caps[0]["available"] is False
    assert "secret" not in caps[0]["unavailable_reason"]


def test_upload_failure_cancels_new_job():
    calls = []
    def handler(request):
        calls.append(request.method)
        if request.method == "POST": return httpx.Response(202, json={"job": job(status="awaiting_upload")})
        if request.method == "DELETE": return httpx.Response(200, json={})
        return httpx.Response(500, text="internal path and token")
    with pytest.raises(WorkerError): client(handler).start(PROJECT, DIGEST, SOURCE)
    assert calls == ["POST", "PUT", "DELETE"]


def test_oversized_worker_response_fails():
    with pytest.raises(WorkerError): client(lambda r: httpx.Response(200, content=b"abc")).request("GET", "/capabilities", limit=2)
