"""Authenticated HTTP export flow. Only the native worker and artifact store are fakes."""
import hashlib
import json
from types import SimpleNamespace
from uuid import uuid4

import httpx
import pytest
from fastapi import FastAPI, HTTPException
from fastapi.testclient import TestClient

from apps.api import ender_exports, readiness_api as api
from apps.api.slicing_worker import SlicingWorker, SETTINGS

PROJECT, JOB = str(uuid4()), str(uuid4())
SOURCE = b"ISO-10303-21; fixture for simulated worker"
DIGEST = hashlib.sha256(SOURCE).hexdigest()
GCODE = b"; generated by PrusaSlicer 2.9.6\nM190 S60\nM109 S205\nG90\nG1 X105 Y105 Z0.2 E1\nG1 X115 Y115 E2\nM104 S0\n"
TOKEN = "test-server-only-token-never-sent-to-browser"
MESH_CONTENT = {
    "stl": (b"solid forma\nendsolid forma\n", "model/stl"),
    "3mf": (b"PK synthetic 3mf fixture", "model/3mf"),
    "obj": (b"o assembly\nv 0 0 0\nv 1 0 0\nv 0 1 0\nf 1 2 3\n", "model/obj"),
}
MESH_DIGESTS = {name: hashlib.sha256(content).hexdigest() for name, (content, _) in MESH_CONTENT.items()}


@pytest.fixture
def rig(monkeypatch):
    calls, saved = [], {}
    state = {"digest": DIGEST, "status": "completed"}
    saved[(PROJECT, DIGEST, api.STEP_MEDIA_TYPE)] = SOURCE
    exports = {}
    for name, (content, media_type) in MESH_CONTENT.items():
        digest = MESH_DIGESTS[name]
        saved[(PROJECT, digest, media_type)] = content
        exports[name] = {
            "filename": f"assembly.{name}",
            "sha256": digest,
            "bytes": len(content),
            "media_type": media_type,
        }
    state["exports"] = exports
    state["meshes"] = []
    class Storage:
        def put(self, project_id, digest, content, media_type):
            saved[(project_id, digest, media_type)] = content
        def get(self, project_id, digest, media_type):
            try: return SimpleNamespace(content=saved[(project_id, digest, media_type)])
            except KeyError as exc: raise FileNotFoundError() from exc
    def handle(request):
        calls.append((request.method, request.url.path))
        assert request.headers["authorization"] == f"Bearer {TOKEN}"
        job = {"job_id": JOB, "project_id": PROJECT, "source_format": "step", "material": "pla",
               "settings": SETTINGS, "printer_profile": "ender3", "status": state["status"],
               "idempotency_key": f"forma-ender-v1:{DIGEST}:nonce", "slicer": "prusaslicer",
               "source_path": "PRIVATE-HOST-PATH", "error": {"code": "slicer_failed", "message": "PRIVATE-HOST-PATH"}}
        if request.url.path == "/capabilities":
            return httpx.Response(200, json={"api_version": 1, "source_formats": ["step"], "printers": [
                {"id": "ender3", "slicer": "prusaslicer", "missing_profile_files": []}, {"id": "bambu-a1-mini"}]})
        if request.url.path == "/slice":
            assert json.loads(request.content)["printer_profile"] == "ender3"
            return httpx.Response(202, json={"job": {**job, "status": "awaiting_upload"}})
        if request.url.path.endswith("/source"):
            assert request.content == SOURCE
            return httpx.Response(202, json={"job": {**job, "status": "running"}})
        if request.url.path.endswith("/artifact"):
            return httpx.Response(200, content=GCODE, headers={"etag": f'"sha256-{hashlib.sha256(GCODE).hexdigest()}"'})
        return httpx.Response(200, json={"job": job})
    monkeypatch.setattr(ender_exports, "enabled", lambda: True)
    monkeypatch.setattr(ender_exports, "_worker", lambda: SlicingWorker("https://worker.example", TOKEN, transport=httpx.MockTransport(handle)))
    monkeypatch.setattr(api, "get_project_identity", lambda pid: {"owner_user_id": "owner", "status": "active"})
    monkeypatch.setattr(api, "get_latest_project_revision", lambda *a: SimpleNamespace(state=SimpleNamespace(cad_model={
        "format": "step",
        "stored_sha256": state["digest"],
        "exports": state["exports"],
        "meshes": state["meshes"],
    })))
    monkeypatch.setattr(api, "ProjectArtifactStorage", Storage)
    monkeypatch.setattr(ender_exports, "ProjectArtifactStorage", Storage)
    monkeypatch.setattr(api, "_step_to_stl", lambda *a: pytest.fail("cloud must not convert CAD"))
    monkeypatch.setattr(api, "resolve_demo_slice_profile", lambda *a: pytest.fail("cloud must not require Orca"))
    app = FastAPI(); app.include_router(api.router)
    app.dependency_overrides[api.require_user_context] = lambda: SimpleNamespace(owner_user_id="owner")
    with TestClient(app) as client:
        yield client, app, calls, saved, state


def test_manifest_generate_poll_persist_and_download(rig):
    client, app, calls, saved, state = rig
    manifest = client.get(f"/projects/{PROJECT}/exports")
    assert manifest.status_code == 200
    value = manifest.json()
    assert [p["printer_id"] for p in value["printers"]] == ["creality_ender_3_04"]
    assert set(value["mesh_exports"]) == {"stl", "3mf", "obj"}
    for name, (content, media_type) in MESH_CONTENT.items():
        descriptor = value["mesh_exports"][name]
        downloaded_mesh = client.get(descriptor["download_url"])
        assert downloaded_mesh.status_code == 200
        assert downloaded_mesh.content == content
        assert downloaded_mesh.headers["content-type"] == media_type
        assert downloaded_mesh.headers["content-disposition"] == f'attachment; filename="assembly.{name}"'
    created = client.post(f"/projects/{PROJECT}/exports/gcode", json={"printer_id": "creality_ender_3_04"})
    assert created.status_code == 200, created.text
    assert created.json()["status"] == "running"
    result = client.get(f"/projects/{PROJECT}/exports/gcode/jobs/{JOB}")
    assert result.status_code == 200, result.text
    value = result.json()
    assert value["status"] == "completed" and value["slicer"] == "prusaslicer"
    assert value["profile_sha256"] is None  # Do not fabricate worker profile hashes.
    assert TOKEN not in result.text and "PRIVATE-HOST-PATH" not in result.text
    downloaded = client.get(value["gcode"]["download_url"])
    assert downloaded.status_code == 200 and downloaded.content == GCODE
    assert hashlib.sha256(downloaded.content).hexdigest() == value["gcode"]["sha256"]
    assert (PROJECT, value["report_sha256"], "application/json") in saved


def test_legacy_revision_preview_mesh_derives_all_portable_downloads(rig):
    client, app, calls, saved, state = rig
    state["exports"] = {}
    state["meshes"] = [{
        "vertices": [0.0, 0.0, 0.0, 10.0, 0.0, 0.0, 0.0, 10.0, 0.0],
        "faces": [0, 1, 2],
    }]
    manifest = client.get(f"/projects/{PROJECT}/exports")
    assert manifest.status_code == 200
    exports = manifest.json()["mesh_exports"]
    assert set(exports) == {"stl", "3mf", "obj"}
    for name, descriptor in exports.items():
        result = client.get(descriptor["download_url"])
        assert result.status_code == 200
        assert result.content
        assert result.headers["content-type"] == api.MESH_EXPORT_MEDIA_TYPES[name]


def test_wrong_owner_cannot_create_poll_or_download(rig):
    client, app, calls, saved, state = rig
    app.dependency_overrides[api.require_user_context] = lambda: SimpleNamespace(owner_user_id="other")
    assert client.post(f"/projects/{PROJECT}/exports/gcode", json={"printer_id": "creality_ender_3_04"}).status_code == 404
    assert client.get(f"/projects/{PROJECT}/exports/gcode/jobs/{JOB}").status_code == 404
    assert client.get(f"/projects/{PROJECT}/exports/gcode/{DIGEST}").status_code == 404
    assert client.get(f"/projects/{PROJECT}/exports/mesh/stl/{MESH_DIGESTS['stl']}").status_code == 404
    assert calls == []


def test_anonymous_poll_uses_existing_auth_dependency(rig):
    client, app, calls, saved, state = rig
    def anonymous(): raise HTTPException(401, "Sign in")
    app.dependency_overrides[api.require_user_context] = anonymous
    assert client.get(f"/projects/{PROJECT}/exports/gcode/jobs/{JOB}").status_code == 401
    assert calls == []


def test_changed_step_and_failed_jobs_are_not_success(rig):
    client, app, calls, saved, state = rig
    state["digest"] = "f" * 64
    assert client.get(f"/projects/{PROJECT}/exports/gcode/jobs/{JOB}").status_code == 409
    state.update(digest=DIGEST, status="failed")
    result = client.get(f"/projects/{PROJECT}/exports/gcode/jobs/{JOB}")
    assert result.status_code == 422
    assert "PRIVATE-HOST-PATH" not in result.text
    assert not any(path.endswith("/artifact") for _, path in calls)


def test_bambu_rejected_in_ender_demo(rig):
    client, app, calls, saved, state = rig
    assert client.post(f"/projects/{PROJECT}/exports/gcode", json={"printer_id": "bambu_a1_04"}).status_code == 422
    assert calls == []
