"use client";

import { Loader2, Printer, Save } from "lucide-react";
import { useId } from "react";
import { useFabricationSettings, type FabricationSettingsState } from "../lib/use-fabrication-settings";

export function FabricationSettingsFields({ state, disabled = false }: {
  state: FabricationSettingsState;
  disabled?: boolean;
}) {
  const selectId = useId();
  const selected = state.settings?.printers.find((printer) => printer.printer_id === state.printerId);
  return <div className="mt-4 space-y-3">
    <div className="grid gap-3 sm:grid-cols-[minmax(0,1fr)_auto] sm:items-end">
      <label htmlFor={selectId} className="block">
        <span className="mb-1.5 block text-[11px] font-medium uppercase tracking-[0.12em] text-[var(--forma-text-muted)]">Printer</span>
        <select id={selectId} value={state.printerId} onChange={(event) => state.selectPrinter(event.target.value)}
          disabled={disabled || state.loading || state.saving || !state.settings}
          className="w-full rounded-lg border border-[var(--forma-border)] bg-[var(--forma-page)] px-3 py-2.5 text-sm text-[var(--forma-text-body)] disabled:opacity-50">
          {!state.settings && <option value="">{state.loading ? "Loading printer settings…" : "Printer settings unavailable"}</option>}
          {state.settings?.printers.map((printer) => <option key={printer.printer_id} value={printer.printer_id}>
            {printer.display_name} · {printer.nozzle_mm.toFixed(1)} mm
          </option>)}
        </select>
      </label>
      <button type="button" onClick={() => void state.save()}
        disabled={disabled || state.loading || state.saving || !state.dirty}
        className="inline-flex min-h-10 items-center justify-center gap-2 rounded-lg border border-[var(--forma-border)] px-3 py-2 text-xs font-medium text-[var(--forma-text-body)] disabled:opacity-50">
        {state.saving ? <Loader2 className="h-4 w-4 animate-spin" /> : <Save className="h-4 w-4" />}
        {state.saving ? "Saving…" : "Save printer preference"}
      </button>
    </div>
    {selected && <p className="text-xs leading-5 text-[var(--forma-text-muted)]">
      {selected.material} · {selected.nozzle_mm.toFixed(1)} mm nozzle · {selected.layer_height_mm.toFixed(2)} mm Standard
    </p>}
    <p className="text-xs leading-5 text-[var(--forma-text-muted)]">
      Saved per account across projects and devices. Material, nozzle and process are included in the reviewed profile; no environment variables are needed.
    </p>
    {state.error && <div role="alert" className="text-xs text-red-500">
      {state.error} {!state.settings && <button type="button" onClick={state.refresh} className="underline">Retry printer settings</button>}
    </div>}
    <p role="status" aria-live="polite" className="text-xs text-[var(--forma-text-muted)]">
      {state.notice || (state.settings ? state.dirty ? "Not saved to your account yet." : "Using your saved printer preference." : "")}
    </p>
  </div>;
}

export default function FabricationSettingsCard() {
  const state = useFabricationSettings();
  return <section className="rounded-xl border border-[var(--forma-border)] bg-[var(--forma-surface)] p-5">
    <h2 className="flex items-center gap-2 text-sm font-semibold text-[var(--forma-text-strong)]"><Printer className="h-5 w-5" />Printer & fabrication</h2>
    <FabricationSettingsFields state={state} />
    <p className="mt-4 text-xs leading-5 text-[var(--forma-text-muted)]">
      G-code is generated by the fabrication worker using its installed OrcaSlicer and bundled profiles. Worker availability does not prevent saving your preference or downloading STEP.
    </p>
  </section>;
}
