-- User-managed developer API keys.
-- Secrets are returned once at creation time; deployed backends require
-- BLUEPRINT_API_KEY_PEPPER and store only keyed HMAC hashes plus metadata.

create table if not exists public.user_api_keys (
  id integer generated by default as identity primary key,
  key_id text not null,
  owner_user_id text not null,
  name text not null,
  key_prefix text not null,
  key_hash text not null,
  scopes jsonb not null default '[]'::jsonb,
  status text not null default 'active',
  rate_limit_per_minute integer not null default 30,
  daily_quota integer not null default 100,
  daily_usage_date text,
  daily_usage_count integer not null default 0,
  created_at text not null,
  last_used_at text,
  expires_at text,
  revoked_at text,
  metadata_json jsonb not null default '{}'::jsonb
);

create unique index if not exists ix_user_api_keys_key_id
  on public.user_api_keys (key_id);

create unique index if not exists ix_user_api_keys_key_hash
  on public.user_api_keys (key_hash);

create index if not exists idx_user_api_keys_owner_user_id
  on public.user_api_keys (owner_user_id);

create index if not exists idx_user_api_keys_status
  on public.user_api_keys (status);

create index if not exists idx_user_api_keys_owner_created_at
  on public.user_api_keys (owner_user_id, created_at desc);

alter table public.user_api_keys
  drop constraint if exists user_api_keys_status_valid;

alter table public.user_api_keys
  add constraint user_api_keys_status_valid
  check (status in ('active', 'revoked'));

alter table public.user_api_keys
  drop constraint if exists user_api_keys_rate_limit_positive;

alter table public.user_api_keys
  add constraint user_api_keys_rate_limit_positive
  check (rate_limit_per_minute > 0);

alter table public.user_api_keys
  drop constraint if exists user_api_keys_daily_quota_positive;

alter table public.user_api_keys
  add constraint user_api_keys_daily_quota_positive
  check (daily_quota > 0);

comment on table public.user_api_keys is
  'Per-user developer API keys. The plaintext secret is shown once at creation; only keyed hashes are stored for verification.';

comment on column public.user_api_keys.owner_user_id is
  'Clerk user id or local-dev-user that owns this API key.';

comment on column public.user_api_keys.key_hash is
  'HMAC-SHA-256 digest of the API key secret using BLUEPRINT_API_KEY_PEPPER in deployed environments.';
