-- Community gallery saves and remix copies.

create table if not exists public.project_saves (
  id integer generated by default as identity primary key,
  project_id text not null,
  owner_user_id text not null,
  created_at text not null
);

create unique index if not exists uq_project_saves_project_user
  on public.project_saves (project_id, owner_user_id);

create index if not exists ix_project_saves_project_id
  on public.project_saves (project_id);

create index if not exists ix_project_saves_owner_user_id
  on public.project_saves (owner_user_id);

create table if not exists public.project_remixes (
  id integer generated by default as identity primary key,
  remix_project_id text not null,
  source_project_id text not null,
  owner_user_id text not null,
  created_at text not null
);

create unique index if not exists ix_project_remixes_remix_project_id
  on public.project_remixes (remix_project_id);

create index if not exists ix_project_remixes_source_project_id
  on public.project_remixes (source_project_id);

create index if not exists ix_project_remixes_owner_user_id
  on public.project_remixes (owner_user_id);
