-- Per-user privacy and product settings.

create table if not exists public.user_settings (
  id integer generated by default as identity primary key,
  owner_user_id text not null,
  model_training_opt_out boolean not null default false,
  created_at text not null,
  updated_at text not null
);

create unique index if not exists ix_user_settings_owner_user_id
  on public.user_settings (owner_user_id);

comment on table public.user_settings is
  'Per-user settings such as privacy preferences and model-training opt-out state.';

comment on column public.user_settings.model_training_opt_out is
  'When true, generated outputs owned by this user should be excluded from model-training datasets.';
