create table if not exists public.user_credit_balances (
  id integer generated by default as identity primary key,
  owner_user_id text not null,
  credit_balance integer not null default 0,
  stripe_customer_id text,
  created_at text not null,
  updated_at text not null
);

create unique index if not exists ix_user_credit_balances_owner_user_id
  on public.user_credit_balances (owner_user_id);

create table if not exists public.user_credit_transactions (
  id integer generated by default as identity primary key,
  owner_user_id text not null,
  credit_delta integer not null,
  balance_after integer not null,
  source text not null,
  stripe_checkout_session_id text,
  stripe_payment_intent_id text,
  metadata_json jsonb not null default '{}'::jsonb,
  created_at text not null
);

create index if not exists ix_user_credit_transactions_owner_user_id
  on public.user_credit_transactions (owner_user_id);

create index if not exists ix_user_credit_transactions_source
  on public.user_credit_transactions (source);

create unique index if not exists ix_user_credit_transactions_stripe_checkout_session_id
  on public.user_credit_transactions (stripe_checkout_session_id);

