-- Initial Supabase schema translated from blueprint.db and blueprint_jobs.db.

create table if not exists public.component_templates (
  id integer generated by default as identity primary key,
  part_number text not null,
  name text not null,
  category text not null,
  description text not null,
  price double precision,
  sourcing_url text,
  pins jsonb not null,
  use_cases jsonb not null
);

create unique index if not exists ix_component_templates_part_number
  on public.component_templates (part_number);

create table if not exists public.generated_projects (
  id integer generated by default as identity primary key,
  project_id text not null,
  title text not null,
  prompt text not null,
  hardware_ir jsonb not null,
  created_at text not null
);

create unique index if not exists ix_generated_projects_project_id
  on public.generated_projects (project_id);

create table if not exists public.a2a_jobs (
  job_id text primary key,
  message_id text not null,
  correlation_id text,
  action text not null,
  sender text not null,
  recipient text not null,
  status text not null,
  server_owned boolean not null default false,
  created_at text not null,
  updated_at text not null,
  started_at text,
  completed_at text,
  payload_json jsonb,
  result_summary_json jsonb,
  error text
);

create index if not exists idx_a2a_jobs_sender
  on public.a2a_jobs (sender);

create index if not exists idx_a2a_jobs_status
  on public.a2a_jobs (status);

create index if not exists idx_a2a_jobs_created_at
  on public.a2a_jobs (created_at);
