-- Add Clerk owner metadata and private chat persistence.
-- Projects remain publicly readable through the API; mutations are owner-scoped in the backend.
-- Chats are private unless a future sharing table/policy grants access.

alter table public.generated_projects
  add column if not exists owner_user_id text,
  add column if not exists visibility text not null default 'public';

alter table public.generated_projects
  drop constraint if exists generated_projects_visibility_valid;

alter table public.generated_projects
  add constraint generated_projects_visibility_valid
  check (visibility in ('public', 'private'));

create index if not exists idx_generated_projects_owner_user_id
  on public.generated_projects (owner_user_id);

create index if not exists idx_generated_projects_visibility
  on public.generated_projects (visibility);

create index if not exists idx_generated_projects_owner_chat
  on public.generated_projects (owner_user_id, chat_id);

create table if not exists public.project_chats (
  id integer generated by default as identity primary key,
  chat_id text not null,
  owner_user_id text not null,
  title text not null,
  messages jsonb not null default '[]'::jsonb,
  created_at text not null,
  updated_at text not null
);

create unique index if not exists ix_project_chats_chat_id
  on public.project_chats (chat_id);

create index if not exists idx_project_chats_owner_user_id
  on public.project_chats (owner_user_id);

create index if not exists idx_project_chats_owner_updated_at
  on public.project_chats (owner_user_id, updated_at desc);

comment on column public.generated_projects.owner_user_id is
  'Clerk user id that owns mutation rights for this public project.';

comment on column public.generated_projects.visibility is
  'Project visibility. Public projects are readable by everyone; owner-scoped mutations are enforced by the API.';

comment on table public.project_chats is
  'Private chat threads keyed by Clerk owner_user_id. Sharing is intentionally deferred to a future ACL table.';
