/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: cf1964b1df112151c41ea1d26b11c106)
interface __BaseEnv_Env {
	PORT: "8000";
	APP_ENV: "production";
	BLUEPRINT_AUTH_MODE: "clerk";
	BLUEPRINT_DEPLOYMENT: "true";
	BLUEPRINT_DEV_MODE: "false";
	BLUEPRINT_DEBUG: "false";
	DATABASE_BACKEND: "supabase";
	BLUEPRINT_IMAGE_STORAGE_BACKEND: "supabase";
	JOB_METADATA_BACKEND: "supabase";
	LLM_PROVIDER: "gemini";
	LLM_MODEL: "gemini-3.5-flash";
	GEMINI_MODEL: "gemini-3.5-flash";
	STRICT_LLM: "true";
	REDIS_CACHE_PREFIX: "forma-production";
	CORS_ALLOWED_ORIGINS: "https://caid-technologies.us,https://www.caid-technologies.us,https://dev.caid-technologies.us,https://staging.caid-technologies.us";
	PUBLIC_FRONTEND_ORIGIN: "https://caid-technologies.us";
	PROJECT_PURGE_WORKER_ENABLED: "false";
	A2A_SOCKET_ENABLED: "false";
	LOG_LEVEL: "INFO";
	FORMA_BACKEND_ENV: string;
	FORMA_API_CONTAINER: DurableObjectNamespace<import("./src/index").FormaApiContainer>;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/index");
		durableNamespaces: "FormaApiContainer";
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "PORT" | "APP_ENV" | "BLUEPRINT_AUTH_MODE" | "BLUEPRINT_DEPLOYMENT" | "BLUEPRINT_DEV_MODE" | "BLUEPRINT_DEBUG" | "DATABASE_BACKEND" | "BLUEPRINT_IMAGE_STORAGE_BACKEND" | "JOB_METADATA_BACKEND" | "LLM_PROVIDER" | "LLM_MODEL" | "GEMINI_MODEL" | "STRICT_LLM" | "REDIS_CACHE_PREFIX" | "CORS_ALLOWED_ORIGINS" | "PUBLIC_FRONTEND_ORIGIN" | "PROJECT_PURGE_WORKER_ENABLED" | "A2A_SOCKET_ENABLED" | "LOG_LEVEL" | "FORMA_BACKEND_ENV">> {}
}
